books/urls.py
from django.urls import path
from .views import index,getJson

urlpatterns = [
	path('', index),
	path('getJson/<str:query>/', getJson, name='getJson'),
]

landing_page/urls.py
from django.urls import path
from .views import index, add_status

urlpatterns = [
	path('', index),
	path('add_status', add_status, name='add_status'),
]

myprofile/urls.py
from django.urls import path
from .views import index

urlpatterns = [
	path('', index),
]

storyaftermidtest/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('landing_page/', include(('landing_page.urls', 'landing_page'), namespace='landing_page')),
    path('profile/', include('myprofile.urls')),
    path('books/', include('books.urls')),
    path('subscribe/', include('subscriber.urls')),
    path('user/', include('user.urls')),
    path('', RedirectView.as_view(url='/landing_page/', permanent=False), name = 'home'),
    path('auth/', include('social_django.urls', namespace='social')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

subscriber/urls.py
from django.urls import path
from .views import index, add_subscriber, check_email, get_subscriber, delete_subscriber

urlpatterns = [
    path('', index, name="index"),
    path('add_subscriber/', add_subscriber, name="add_subscriber"),
    path('check_email', check_email, name="check_email"),	
    path('get_subscriber', get_subscriber, name="get_subscriber"),
    path('delete_subscriber', delete_subscriber, name="delete_subscriber"),	
]

user/urls.py
from django.urls import path
from .views import pull_data, push_data, update_data, get_data

urlpatterns = [
    path('pull_data/', pull_data, name="pull_data"),
    path('push_data/', push_data, name="push_data"),	
    path('update_data/<str:query>/', update_data, name="update_data"),	
    path('get_data/', get_data, name="get_data"),	

]

books/models.py
from django.db import models

# Create your models here.

landing_page/models.py
from django.db import models
from django.utils import timezone

class Status(models.Model):
	status = models.CharField(max_length=300)
	date = models.DateTimeField(default = timezone.now)

myprofile/models.py
from django.db import models

# Create your models here.

subscriber/models.py
from django.db import models
from django.core.validators import MinLengthValidator

class Subscriber(models.Model):
    name = models.CharField(max_length=70)
    email = models.EmailField(max_length=255, unique=True)
    password = models.CharField(max_length=32, validators=[MinLengthValidator(8)])
    

	
    

user/models.py
from django.db import models
from django.utils import timezone

class User(models.Model):
	username = models.CharField(max_length = 255)
	books_list = models.TextField()

landing_page/forms.py
from django.forms import ModelForm
from django import forms
from .models import Status

class StatusForm(ModelForm):

    status = forms.CharField(max_length=300, widget=forms.TextInput(
    	attrs={
    		'class': 'form-control',
    		'placeholder': 'Apakah ada sesuatu yang terjadi ...?',
    	}
    ))

    class Meta:
        model = Status
        fields = 'status',

subscriber/forms.py
from django import forms
from .models import Subscriber

class SubscribeForm(forms.ModelForm):

    name = forms.CharField(max_length=70, widget=forms.TextInput(
    	attrs={
    		'class': 'form-control',
    		'placeholder': 'Your name ...',
    	}
    ))

    email = forms.CharField(max_length=255, widget=forms.EmailInput(
    	attrs={
    		'class': 'form-control',
    		'placeholder': 'email@example.com',
    	}
    ))

    password = forms.CharField(max_length=32, widget=forms.PasswordInput(
    	attrs={
    		'class': 'form-control',
    		'placeholder': 'Your password ...',
    	}
    ))

    class Meta:
        model = Subscriber
        fields = '__all__'

books/views.py
from django.shortcuts import render
from django.http import JsonResponse
import json
import requests

response = {}

def getJson(request, query):
	url = 'https://www.googleapis.com/books/v1/volumes?q=' + query
	json_data = json.loads(requests.get(url).text)
	return JsonResponse(json_data)

def index(request):
	return render(request, 'books.html', response)

landing_page/views.py
from django.shortcuts import render
from .forms import StatusForm
from.models import Status
from django.http import HttpResponseRedirect

response = {}
# Create your views here.
def index(request):
	status = Status.objects.all().values().order_by('date').reverse()
	response['status'] = status
	response['StatusForm'] = StatusForm
	return render(request, 'index.html', response)

def add_status(request):
	form = StatusForm(request.POST or None)
	if request.method == 'POST' and form.is_valid():
		status = Status(status=request.POST['status'])
		status.save()
		return HttpResponseRedirect("/../landing_page/")
	response['StatusForm'] = form
	return render(request, "index.html", response)

myprofile/views.py
from django.shortcuts import render

response = {}
# Create your views here.
def index(request):
	return render(request, 'profile.html', response)

subscriber/views.py
from django.shortcuts import render
from .forms import SubscribeForm
from .models import Subscriber
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.http import JsonResponse
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.core import serializers
response = {}


# Create your views here.
def index(request):
    response['SubscribeForm'] = SubscribeForm
    return render(request, 'subscribe.html', response)

def add_subscriber(request):
    form = SubscribeForm(request.POST)
    if form.is_valid():
        form.save()
        return JsonResponse({'success': True})
    response =  JsonResponse({'success': False, 'errors':form.errors})
    response.status_code = 403
    return response

def check_email(request):
    email = request.GET.get('email', '')
    response = {'valid' : None, 'exists': None, 'messages': []}
    try:
        validate_email(email)
    except ValidationError as error:
        response['valid'] = False
        response['messages'] = error.messages
    else:
        response['valid'] = True
        if Subscriber.objects.filter(email=email):
            response['exists'] = True
            response['messages'] = ["Subscriber with this email already exists"]
        else:
            response['exists'] = False
    return JsonResponse(response)

def get_subscriber(request):
    data = list(Subscriber.objects.values())
    data.reverse()
    response = {'data': data}
    return JsonResponse(response)

def delete_subscriber(request):
    email = request.GET.get('email', '')
    password = request.GET.get('password', '')
    response = {'EmailExists' : False, 'PasswordConfirm' : False}
    object = Subscriber.objects.filter(email=email)
    
    if object :
        response['EmailExists'] = True
        user_password = list(object.values_list('password', flat=True))[0]
        if password==user_password:
            response['PasswordConfirm'] = True
            object.delete()
            return JsonResponse(response)
    return JsonResponse(response)

user/views.py
from django.shortcuts import render
from.models import User
from django.http import HttpResponseRedirect
import json
from django.http import JsonResponse

response = {}
# Create your views here.
def pull_data(request):
	if request.user.is_authenticated:
		object = User.objects.filter(username=request.user.username)
		if (object):
			object = User.objects.get(username=request.user.username)
			request.session['books_list'] = json.loads(object.books_list)
		else:	
			member = User.objects.create(username=request.user.username, books_list="[]")
			request.session['books_list'] = []
	return HttpResponseRedirect("../../landing_page")

def push_data(request):
	object = User.objects.get(username=request.user.username)
	object.books_list = json.dumps(request.session['books_list'])
	object.save()
	request.session.flush()
	return HttpResponseRedirect("../../logout")

def update_data(request, query):
	if query in request.session['books_list']:
		request.session['books_list'].remove(query)
		response['Remove'] = True
		response['Add'] = False
		request.session.modified = True
	else:
		request.session['books_list'].append(query)
		response['Remove'] = False
		response['Add'] = True
		request.session.modified = True
	return JsonResponse(response)

def get_data(request):
	if request.user.is_authenticated:
		response['loggedIn'] = True
		response['data'] = request.session['books_list']
	else:
		response['loggedIn'] = False
		response['data'] = []
	return JsonResponse(response)

books/templates/books.html
{% extends "base.html" %}

<!DOCTYPE html>
<html>
<head>
	{% load static %}
	{% block heading %}
	<title>Books | Ahmad Fauzan Amirul Isnain</title>
	<script src="{% static 'js/books.js' %}"> </script>
	{% endblock heading %}
</head>
<body>
{% block content %}	
	<div class="main main-landing-page">
		<div class="title">
			<h1>Books</h1>
		</div>
		<div class="row">
    		<div class="col-12">
				<div class ="main-form">
					<div class ="form-container">
						<div class="form-group row">
						  	<div class="col-10 center">
						    	<input type="text" id="search-box" class="form-control" placeholder="Search..." maxlength="300">
						  	</div>
						</div>
			        	<div class="form-group row">
							<button id="search-button" name="search-button" class="status-button save btn btn-primary center">Search</button>
							<button id="show-fav-button" name="show-fav-button" class="status-button save btn btn-primary center">Show Favorite Books ID</button>
						</div>
				   	</div>
			   </div>
    		</div>
		</div>
		<h3 id="fav-count">Favorite Count: </h3>
		<div id="fav-list">
			<h5>Your favorite books' ID list:</h5>
			<p>*Your can search your favorite books at search box using the ID</p>"
			<div class="table-responsive">
				<table class="table">
				  <thead class="thead-dark text-center">
				    <tr>
				      <th scope="col">ID</th>
				    </tr>
				  </thead>
				  <tbody id="fav-list-content" class="text-center">
				  </tbody>
				</table>
			</div>'
		</div>
		<div class='table-responsive'>
			<table class="table">
			  <thead class="thead-dark text-center">
			    <tr>
			      <th scope="col">No.</th>
			      <th scope="col">Image</th>
			      <th scope="col">Title</th>	
			      <th scope="col">Authors</th>
			      <th scope="col">Publisher</th>
			      <th scope="col">Published Date</th>
			      <th scope="col">Favorite</th>
			    </tr>
			  </thead>
			  <tbody id="books-body" class="text-left">
			  </tbody>
			</table>
		</div>
	</div>
{% endblock content %}	
</body>
</html>

landing_page/templates/index.html
{% extends "base.html" %}

<!DOCTYPE html>
<html>
<head>
	{% load static %}
	{% block heading %}
	<title>Hello World | Ahmad Fauzan Amirul Isnain</title>
	{% endblock heading %}
</head>
<body>
{% block content %}	
	<div class="main main-landing-page">
		<div class="title">
			{% if user.is_authenticated %}
			<h1>Hello, Apa kabar {{ user.username }}?</h1>
			{% else %}
			<h1>Hello, Apa kabar?</h1>
			{% endif %}
		</div>
		<div class="row">
    		<div class="col-12">
				<div class ="main-form">
					<div class ="form-container">
				    	<form method="POST" action="{% url 'landing_page:add_status' %}">
				    		{% csrf_token %}
					    		{% for data in StatusForm %}
									<div class="form-group row">
									  	<div class="col-10 center">
									    	{{data}}
									    	{% if data.errors %}
									    		{{data.errors}}
									    	{% endif %}
									  	</div>
									</div>
								{% endfor %}
				        	<div class="form-group row">
								<button type="submit" class="status-button save btn btn-primary center">Post</button>
							</div>
				   		</form>
				   	</div>
			   </div>
    		</div>
		</div>
	   <div class="status">
	   		{% for data in status %}
				<div class="panel panel-default">
					<div class="panel-body panel-body-landing border border-dark">
						<div class="status-message">
							<p>{{data.status}}</p>
						</div>
						<div class='right'>
							<p>{{data.date}}</p>
						</div>
					</div>
				</div>
			{% endfor %}
	   </div>
	</div>
{% endblock content %}	
</body>
</html>

myprofile/templates/profile.html
{% extends "base.html" %}

<!DOCTYPE html>
<html>
<head>
	{% load static %}
	{% block heading %}
	<title>Profile | Ahmad Fauzan Amirul Isnain</title>
	{% endblock heading %}
</head>
</style>
<body>
{% block content %}
	<div class ="main">
		<div class="container container-homepage-1">
			<div class="panel-group">
				<div class="panel panel-default border border-dark header">
					<div class="panel-heading">
						<a name="header">
							<img class="img-responsive header-img-1" id="header-img" src="{% static 'img/header.png' %}">
							<img class="img-responsive header-img-2" id="header-img-2" src="{% static 'img/header-green.jpg' %}">
						</a>
						<img class="img-responsive" id="profile_photo" src="{% static 'img/profile_photo.jpg' %}">
					</div>
					<div class="panel-body">
						<div class="container">
							<div class="row header-versi-satu">
								<div class="col-8">
									<h1>Ahmad Fauzan Amirul Isnain</h1>
									<h2>Student at Universitas Indonesia</h2>
								</div>
								<div class="col-4 header-margin-bottom">
									<h2>Contact</h2>
									<div class="row">
										<img class="inline" src="{% static 'img/email.png' %}">
										<p class="inline">ahmad.fauzan4580@gmail.com</p>
									</div>
									<div class="row">
										<img class="inline" src="{% static 'img/call.png' %}">
										<p class="inline">087775639862</p>
									</div>
								</div>
							</div>
							<div class="row header-versi-dua">
								<div class="col-12">
									<h1>Ahmad Fauzan Amirul Isnain</h1>
									<h2>Student at Universitas Indonesia</h2>
								</div>
								<div class="col-12 auto-margin">
									<div class="row auto-margin">
										<img class="inline" src="{% static 'img/email.png' %}">
										<p class="inline">ahmad.fauzan4580@gmail.com</p>
									</div>
									<div class="row auto-margin">
										<img class="inline" src="{% static 'img/call.png' %}">
										<p class="inline">087775639862</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading accordion panel-heading-custom border border-dark">
						<h1><a name="current-activity">Current Activity</a></h1>
					</div>
					<div class="panel-body accordion-body panel-body-custom border border-dark">
						<div class="row content">
							<img src="{% static 'img/fuki.png' %}">
							<div class="inline content-word">
								<p>Staff of Muslim Development Center</p>
								<p>Forum Ukhuwah dan Kajian Islam Fasilkom UI</p>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div name ="experience-head" class="panel-heading accordion panel-heading-custom border border-dark">
						<h1><a name="Experience">Experience</a></h1>
					</div>
					<div name="experience-body" class="panel-body accordion-body panel-body-custom border border-dark">
						<div class="row content">
							<img src="{% static 'img/compfest.png' %}">
							<div class="inline content-word">
								<p>Staff of Equipment and Security</p>
								<p>Compfest X</p>
								<p>Feb, 2018 - Sept, 2018</p>
							</div>
						</div>
						<div class="row content">
							<img src="{% static 'img/fuki.png' %}">
							<div class="inline content-word">
								<p>Staff of Muslim Development Center</p>
								<p>Forum Ukhuwah dan Kajian Islam Fasilkom UI</p>
								<p>Feb, 2018 - Present</p>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading accordion panel-heading-custom border border-dark">
						<h1><a name="Education">Education</a></h1>
					</div>
					<div class="panel-body accordion-body panel-body-custom border border-dark">
						<div class="row content">
							<img src="{% static 'img/UI.png' %}">
							<div class="inline content-word"/>
								<p>Universitas Indonesia</p>
								<p>Bachelor’s  degree, Computer Science</p>
								<p>2017 - Present</p>
							</div>
						</div>
						<div class="row content">
							<img src="{% static 'img/smanda.png' %}"/>
							<div class="inline content-word">
								<p>SMA Negeri 2 Bogor</p>
								<p>2014 - 2017</p>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading accordion panel-heading-custom border border-dark">
						<h1><a name="Skills">Skills</a></h1>
					</div>
					<div class="panel-body accordion-body panel-body-custom border border-dark">
						<div class="row content">
							<img src="{% static 'img/java.png' %}">
							<div class="inline content-word">
								<p>Java</p>
								<p>Object Oriented Programming</p>
							</div>
						</div>
						<div class="row content">
							<img src="{% static 'img/python.png' %}">
							<div class="inline content-word">
								<p>Python</p>
								<p>Procedural Programming</p>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading accordion panel-heading-custom border border-dark">
						<h1><a name="Accomplishments">Accomplishments</a></h1>
					</div>
					<div class="panel-body accordion-body panel-body-custom border border-dark">
						<div class="row content">
							<img src="{% static 'img/fastfingers.png' %}">
							<div class="inline content-word">
								<p>98 WPM English Typing Speed Test</p>
								<p>10FastFingers</p>
								<p>2018</p>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading accordion panel-heading-custom border border-dark">
						<h1><a name="Interests">Interests</a></h1>
					</div>
					<div class="panel-body accordion-body panel-body-custom border border-dark">
						<div class="row content">
							<img src="{% static 'img/se.png' %}">
							<div class="inline content-word">
								<p>Software Engineering</p>
								<p>Apply principles and techniques of computer science to<br/>
								software applications for computer</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container container-homepage-2">
						<div class="panel-group">
				<div class="panel panel-default border border-dark header">
					<div class="panel-heading">
						<a name="header2">
							<img class="img-responsive header-img-1" id="header-img" src="{% static 'img/header.png' %}">
							<img class="img-responsive header-img-2" id="header-img-2" src="{% static 'img/header-green.jpg' %}">
						</a>
						<img class="img-responsive" id="profile_photo" src="{% static 'img/profile_photo.jpg' %}">
					</div>
					<div class="panel-body">
						<div class="container">
							<div class="row header-versi-satu">
								<div class="col-8">
									<h1>Ahmad Fauzan Amirul Isnain</h1>
									<h2>Student at Universitas Indonesia</h2>
								</div>
								<div class="col-4 header-margin-bottom">
									<h2>Contact</h2>
									<div class="row">
										<img class="inline" src="{% static 'img/email.png' %}">
										<p class="inline">ahmad.fauzan4580@gmail.com</p>
									</div>
									<div class="row">
										<img class="inline" src="{% static 'img/call.png' %}">
										<p class="inline">087775639862</p>
									</div>
								</div>
							</div>
							<div class="row header-versi-dua">
								<div class="col-12">
									<h1>Ahmad Fauzan Amirul Isnain</h1>
									<h2>Student at Universitas Indonesia</h2>
								</div>
								<div class="col-12 auto-margin">
									<div class="row auto-margin">
										<img class="inline" src="{% static 'img/email.png' %}">
										<p class="inline">ahmad.fauzan4580@gmail.com</p>
									</div>
									<div class="row auto-margin">
										<img class="inline" src="{% static 'img/call.png' %}">
										<p class="inline">087775639862</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading accordion panel-heading-custom border border-dark">
						<h1><a name="current-activity2">Current Activity</a></h1>
					</div>
					<div class="panel-body accordion-body panel-body-custom border border-dark">
						<div class="row content">
							<img class="auto-margin" src="{% static 'img/fuki.png' %}">
						</div>
						<div class="row content">
							<div class="inline content-word">
								<p>Staff of Muslim Development Center</p>
								<p>Forum Ukhuwah dan Kajian Islam Fasilkom UI</p>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading accordion panel-heading-custom border border-dark">
						<h1><a name="Experience2">Experience</a></h1>
					</div>
					<div class="panel-body accordion-body panel-body-custom border border-dark">
						<div class="row content">
							<img class="auto-margin" src="{% static 'img/compfest.png' %}">
						</div>
						<div class="row content">
							<div class="inline content-word">
								<p>Staff of Equipment and Security</p>
								<p>Compfest X</p>
								<p>Feb, 2018 - Sept, 2018</p>
							</div>
						</div>
						<div class="row content">
							<img class="auto-margin" src="{% static 'img/fuki.png' %}">
						</div>
						<div class="row content">
							<div class="inline content-word">
								<p>Staff of Muslim Development Center</p>
								<p>Forum Ukhuwah dan Kajian Islam Fasilkom UI</p>
								<p>Feb, 2018 - Present</p>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading accordion panel-heading-custom border border-dark">
						<h1><a name="Education2">Education</a></h1>
					</div>
					<div class="panel-body accordion-body panel-body-custom border border-dark">
						<div class="row content">
							<img class="auto-margin" src="{% static 'img/UI.png' %}">
						</div>
						<div class="row content">
							<div class="inline content-word"/>
								<p>Universitas Indonesia</p>
								<p>Bachelor’s  degree, Computer Science</p>
								<p>2017 - Present</p>
							</div>
						</div>
						<div class="row content">
							<img class="auto-margin" src="{% static 'img/smanda.png' %}"/>
						</div>
						<div class="row content">
							<div class="inline content-word">
								<p>SMA Negeri 2 Bogor</p>
								<p>2014 - 2017</p>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading accordion panel-heading-custom border border-dark">
						<h1><a name="Skills2">Skills</a></h1>
					</div>
					<div class="panel-body accordion-body panel-body-custom border border-dark">
						<div class="row content">
							<img class="auto-margin" src="{% static 'img/java.png' %}">
						</div>
						<div class="row content">
							<div class="inline content-word">
								<p>Java</p>
								<p>Object Oriented Programming</p>
							</div>
						</div>
						<div class="row content">
							<img class="auto-margin" src="{% static 'img/python.png' %}">
						</div>
						<div class="row content">
							<div class="inline content-word">
								<p>Python</p>
								<p>Procedural Programming</p>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading accordion panel-heading-custom border border-dark">
						<h1><a name="Accomplishments2">Accomplishments</a></h1>
					</div>
					<div class="panel-body accordion-body panel-body-custom border border-dark">
						<div class="row content">
							<img class="auto-margin" src="{% static 'img/fastfingers.png' %}">
						</div>
						<div class="row content">
							<div class="inline content-word">
								<p>98 WPM English Typing Speed Test</p>
								<p>10FastFingers</p>
								<p>2018</p>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading accordion panel-heading-custom border border-dark">
						<h1><a name="Interests2">Interests</a></h1>
					</div>
					<div class="panel-body accordion-body panel-body-custom border border-dark">
						<div class="row content">
							<img class="auto-margin" src="{% static 'img/se.png' %}">
						</div>
						<div class="row content">
							<div class="inline content-word">
								<p>Software Engineering</p>
								<p>Apply principles and techniques of computer science to<br/>
								software applications for computer</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}
</body>
</html>

subscriber/templates/subscribe.html
{% extends "base.html" %}

<!DOCTYPE html>
<html>
<head>
	{% load static %}
	{% block heading %}
	<title>Hello World | Ahmad Fauzan Amirul Isnain</title>
	<script src="{% static 'js/subscribe.js' %}"> </script>
	{% endblock heading %}
</head>
<body>
{% block content %}	
	<div class="main main-landing-page">
		<div class="title">
			<h1>Subscribe me</h1>
		</div>
		<div class="row">
    		<div class="col-12">
				<div class ="main-form">
					<div class ="form-container" id="subscribe-form">
				    	<form method="POST">
				    		{% csrf_token %} 
					    		{% for data in SubscribeForm %}
									<div class="form-group row">
									  	<div class="col-10 center">
									    	{{data}}
									    	<div class="form-errors" id ="{{data.name}}_errors"></div>
									    	{% if data.name == 'password' %}
									    	<div class="form-check">
									    		<input id="toggle-password" class="form-check-input" type="checkbox">
									    		<label class="form-check-label" for="toggle-password">Reveal Password</label>
									    	</div>
									    	{% endif %}
									  	</div>
									</div>
								{% endfor %}
				        	<div class="form-group row">
								<button type="submit" class="status-button save btn btn-primary center" id="submit_button" disabled="true">Submit</button>
							</div>
							<div class="alert alert-success">Data successfully recorded</div>
							<div class="alert alert-danger">Something went wrong, please try again</div>
				   		</form>
				   	</div>
			   </div>
				<div id="subscriber-list">
					<h5>Subscriber list:</h5>
					<div class="table-responsive">
						<table class="table">
						  <thead class="thead-dark text-center">
						    <tr>
						      <th scope="col">Name</th>
						      <th scope="col">Email</th>
						      <th scope="col">Button</th>
						    </tr>
						  </thead>
						  <tbody id="subscriber-list-content" class="text-center">
						  </tbody>
						</table>
					</div>
				</div>
    		</div>
		</div>
		<div class="modal fade" id="modal-unsubscribe" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
		  <div class="modal-dialog modal-dialog-centered" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <h5 class="modal-title" id="modal-unsubscribe-title">Enter your password to unsubscribe</h5>
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
		          <span aria-hidden="true">&times;</span>
		        </button>
		      </div>
		      <div class="modal-body">
		        <input type="password" name="password-unsub" class="form-control" placeholder="Your password ..." maxlength="32" required="" id="password-unsub">
				<div class="form-check">
		    		<input id="toggle-confirm-password" class="form-check-input" type="checkbox">
		    		<label class="form-check-label" for="toggle-confirm-password">Reveal Password</label>
		    	</div>
		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
		        <button type="button" class="btn btn-primary" id="confirm-pass-unsub-btn">Confirm</button>
		      </div>
		    </div>
		  </div>
		</div>
		<div class="modal fade" id="modal-template" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
		  <div class="modal-dialog modal-dialog-centered" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <h5 class="modal-title" id="modal-template-title"></h5>
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
		          <span aria-hidden="true">&times;</span>
		        </button>
		      </div>
		      <div class="modal-body">
		        <p class="modal-body-text" id="modal-template-p"></p>
		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
		      </div>
		    </div>
		  </div>
		</div>
	</div>
{% endblock content %}	
</body>
</html>